# Generated by Django 5.1.6 on 2025-05-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('target_audience', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('creatives', models.TextField(null=True)),
                ('count_requested', models.PositiveIntegerField(null=True)),
                ('project_profile', models.TextField(null=True)),
            ],
        ),
    ]
