# Generated by Django 5.1.6 on 2025-05-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevantChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_post_date', models.DateTimeField(null=True)),
                ('profile_channel', models.TextField(null=True)),
                ('keywords_channel', models.TextField(null=True)),
                ('score', models.FloatField(null=True)),
                ('new_creatives', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevant_channels', to='tgservice.project')),
            ],
        ),
    ]
