# Generated by Django 5.1.6 on 2025-05-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0002_category_worksheet_channel_message_relevantchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('text_messages', models.TextField(null=True)),
                ('text_length', models.IntegerField(null=True)),
                ('first_post_date', models.DateField(null=True)),
                ('last_post_date', models.DateField(null=True)),
                ('total_posts', models.IntegerField(null=True)),
                ('active_months', models.IntegerField(null=True)),
                ('profile_channel', models.TextField(null=True)),
                ('profile_intokens', models.IntegerField(null=True)),
                ('profile_outtokens', models.IntegerField(null=True)),
                ('keywords_channel', models.TextField(null=True)),
                ('keywords_intokens', models.IntegerField(null=True)),
                ('keywords_outtokens', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tgservice.category')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tgservice.channel')),
            ],
        ),
    ]
