# Generated by Django 5.1.6 on 2025-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0003_category_worksheet_channel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevantchannel',
            name='last_post_date',
            field=models.DateField(null=True),
        ),
    ]
