# Generated by Django 5.1.6 on 2025-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0003_newproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('text_messages', models.TextField()),
                ('text_length', models.IntegerField()),
                ('first_post_date', models.DateField()),
                ('last_post_date', models.DateField()),
                ('total_posts', models.IntegerField()),
                ('active_months', models.IntegerField()),
                ('profile_channel', models.TextField()),
                ('profile_intokens', models.IntegerField()),
                ('profile_outtokens', models.IntegerField()),
                ('keywords_channel', models.TextField()),
                ('keywords_intokens', models.IntegerField()),
                ('keywords_outtokens', models.IntegerField()),
            ],
        ),
    ]
