# Generated by Django 5.1.6 on 2025-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0004_worksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_intokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_outtokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_intokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_outtokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
