# Generated by Django 5.1.6 on 2025-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0004_alter_relevantchannel_last_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevantchannel',
            name='channel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='relevantchannel',
            unique_together={('project', 'channel_name')},
        ),
    ]
