# Generated by Django 5.1.6 on 2025-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0005_alter_worksheet_keywords_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='active_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='first_post_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='last_post_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='subscribers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='text_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='text_messages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='total_posts',
            field=models.IntegerField(null=True),
        ),
    ]
