# Generated by Django 5.1.6 on 2025-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0006_alter_worksheet_active_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_channel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_intokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='keywords_outtokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_channel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_intokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_outtokens',
            field=models.IntegerField(null=True),
        ),
    ]
