# Generated by Django 5.1.6 on 2025-04-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgservice', '0007_alter_worksheet_keywords_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('creatives', models.TextField(null=True)),
                ('count_requested', models.PositiveIntegerField(null=True)),
                ('project_profile', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelevantChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_post_date', models.DateTimeField(null=True)),
                ('profile_channel', models.TextField(null=True)),
                ('keywords_channel', models.TextField(null=True)),
                ('score', models.FloatField(null=True)),
                ('project_profile', models.TextField(null=True)),
                ('new_creatives', models.TextField(null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tgservice.project')),
            ],
        ),
        migrations.DeleteModel(
            name='NewProject',
        ),
    ]
